# This job is to test different profiles in sdk branch against full commit id
# This workflow targets nunit
name: C-sharp SDK Test workflow on workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full commit id to build'
        required: true

jobs:
  comment-run:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        dotnet: ['6.0.x']
    name: NUnit Appium Repo ${{ matrix.dotnet }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-in-progress
        env:
          job_name: NUnit Appium Repo ${{ matrix.dotnet }} - ${{ matrix.os }} Sample
          commit_sha: ${{ github.event.inputs.commit_sha }}
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.job_name,
              head_sha: process.env.commit_sha,
              status: 'in_progress'
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear
      
      - name: Restore dependencies
        run: |
          cd android
          dotnet restore

      - name: Install test adapters
        run: |
          dotnet add android/android.csproj package Microsoft.NET.Test.Sdk
          dotnet add android/android.csproj package NUnit
          dotnet add android/android.csproj package NUnit3TestAdapter
          dotnet add android/android.csproj package Microsoft.TestPlatform.TestHost

      - name: Build and Test Android
        shell: pwsh
        run: |
          Write-Host "Current directory: $(Get-Location)"
          cd android
          Write-Host "Building project..."
          dotnet build --configuration Release
          Write-Host "Running tests..."
          dotnet test --no-build --configuration Release --verbosity diagnostic

      - name: Run sample android tests
        shell: pwsh
        run: |
          cd android
          dotnet test --filter "Category=sample-test" --verbosity normal
        env: 
          BROWSERSTACK_APP: ./WikipediaSample.apk

      - name: Run local android tests
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5  # Prevent file access conflicts
          cd android
          dotnet test --filter "Category=sample-local-test"
        env: 
          BROWSERSTACK_APP: ./LocalSample.apk

      - name: Run sample ios tests
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5  # Prevent file access conflicts
          cd ios
          dotnet test --filter "Category=sample-test"

      - name: Run local ios tests
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5  # Prevent file access conflicts
          cd ios
          dotnet test --filter "Category=sample-local-test"
        env: 
          BROWSERSTACK_APP: ./LocalSample.ipa

      - if: always()
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-completed
        env:
          conclusion: ${{ job.status }}
          job_name: NUnit Appium Repo ${{ matrix.dotnet }} - ${{ matrix.os }} Sample
          commit_sha: ${{ github.event.inputs.commit_sha }}
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: process.env.job_name,
            head_sha: process.env.commit_sha,
            status: 'completed',
            conclusion: process.env.conclusion
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }
